version: "3"

services:
  api:
    build: api/
    command: node ./dist/src/main.js
    ports:
      - "3000:3000"
    networks:
      - api
    depends_on:
      - postgres

  postgres:
    image: "postgres:11-alpine"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=short-messages
    volumes:
      - sm-pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - api
      - db

  pgadmin:
    image: dpage/pgadmin4:4.24
    restart: always
    ports:
      - "8022:80"
    volumes:
      - sm-pg-admin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - db
    depends_on:
      - postgres

volumes:
  sm-pg-data:
  sm-pg-admin:

networks:
  api:
  db:
